# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
        files: ^(src/.+\.py|scripts/.+\.py|install.py)
    -   id: trailing-whitespace
        files: ^(src/.+\.py|scripts/.+\.py|install.py)
-   repo: https://github.com/google/yapf
    rev: v0.40.1
    hooks:
    -   id: yapf
        entry: yapf
        language: python
        files: ^(src/.+\.py|scripts/.+\.py|install.py)
        types: [python]
        args: [-i, -p, -r]
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8