paths:
  base_paths:
    TNG300-1: /virgotng/universe/IllustrisTNG/TNG300-1/output
    TNG50-4: /virgotng/universe/IllustrisTNG/TNG50-4/output
    TNG50-3: /virgotng/universe/IllustrisTNG/TNG50-3/output
    TNG-Cluster: /virgotng/mpia/TNG-Cluster/TNG-Cluster/output
  # Set to 'default' to create directories inside the project directory.
  # Otherwise, use full paths to data and/or figures home directory.
  data_home: default
  figures_home: default