[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "src/tests",
    "src/**/tests",
]
pythonpath = "src"

[tool.isort]
profile = "black"
src_paths = ["src", "notebooks", "pipelines", "scripts"]
skip_glob = ["docs/*", "external/*"]