Temperature:
  min: 3  # log scale
  max: 9  # log scale
  log: true
  individual-log: true
Density:
  min: 0  # log scale
  max: 12  # log scale
  log: true
  individual-log: true
DistanceToMP:
  min: 0  # log scale
  max: 6  # log scale
  log: true
  individual-log: false
Mass:
  min: 6  # log scale
  max: 10  # log scale
  log: true
  individual-log: true