sfr:
  default-scale: log
  daq-field-name: GroupSFR
  label:
    log: "SFR [$\\log(M_\\odot / yr)$]"
    linear: "SFR [$M_\\odot / yr$]"
    dev: ["\\rm SFR", "Total SFR in halo"]
  cbar-config:
    norm: default
    vmin:
      log: 0.0
    vmax:
      log: 2.0
    cmap: viridis
    caps: both
  dev-config:
    default-scale: log
    limits-log: [-1, 1]
    limits-linear: [0, 4]

sfr-central:
  default-scale: log
  daq-field-name: SFRCore
  label:
    log: "Central SFR [$\\log(M_\\odot / yr)$]"
    linear: "Central SFR [$M_\\odot / yr$]"
    dev: ["\\rm SFR_c", "SFR in central galaxy"]
  cbar-config:
    norm: default
    vmin:
      log: -1.0
    vmax:
      log: 2.0
    cmap: viridis
    caps: both
  dev-config:
    default-scale: log
    limits-log: [-3, 3]
    limits-linear: [0, 4]

gas-metallicity:
  default-scale: linear
  daq-field-name: GroupGasMetallicity
  label:
    log: "Gas metallicity [$\\log Z_\\odot$]"
    linear: "Gas metallicity [$Z_\\odot$]"
    dev: ["Z", "Gas metallicity in cluster"]
  cbar-config:
    norm: default
    cmap: cividis
  dev-config:
    default-scale: log
    limits-log: [-0.075, 0.075]
    limits-linear: [0.8, 1.2]

gas-metallicity-central:
  default-scale: linear
  daq-field-name: GasMetallicityCore
  label:
    log: "Central gas metallicity [$\\log Z_\\odot$]"
    linear: "Central gas metallicity [$Z_\\odot$]"
    dev: ["Z_{\\rm c}", "Gas metallicity in central galaxy"]
  cbar-config:
    norm: default
    cmap: cividis
    vmax:
      linear: 0.7
    caps: max
  dev-config:
    default-scale: log
    limits-log: [-0.3, 0.3]
    limits-linear: [0.8, 1.2]

massive-satellites:
  default-scale: log
  daq-field-name: MassiveSatellites
  label:
    log: "Number of satellites with $M_* > 10^{9} M_\\odot$ [$\\log_{10}$]"
    linear: "Number of satellites with $M_* > 10^{9} M_\\odot$"
    dev: ["N_{\\rm sat}", "Number of massive satellites"]
  cbar-config:
    norm: default
    cmap: cmr.ghostlight
  dev-config:
    default-scale: log
    limits-log: [-0.2, 0.2]
    limits-linear: [0, 4]

stellar-mass:
  default-scale: log
  daq-field-name: TotalStellarMass
  label:
    log: "Stellar mass of FoF group [$\\log_{10} M_\\odot$]"
    linear: "Stellar mass of FoF group [$M_\\odot$]"
    dev: ["M_{\\ast,\\rm halo}", "Stellar mass in cluster"]
  cbar-config:
    norm: default
    cmap: cmr.eclipse
  dev-config:
    default-scale: log
    limits-log: [-0.2, 0.2]
    limits-linear: [0, 4]

stellar-mass-central:
  default-scale: log
  daq-field-name: CentralStellarMass
  label:
    log: "Stellar mass of central galaxy [$\\log_{10} M_\\odot$]"
    linear: "Stellar mass of central galaxy [$M_\\odot$]"
    dev: ["M_{\\ast,\\rm central}", "Stellar mass in central galaxy"]
  cbar-config:
    norm: default
    cmap: cmr.eclipse
  dev-config:
    default-scale: log
    limits-log: [-0.2, 0.2]
    limits-linear: [0, 4]

total-bh-mass:
  default-scale: log
  daq-field-name: TotalBHMass
  label:
    log: "Total SMBH mass [$\\log M_\\odot$]"
    linear: "Total SMBH mass [$M_\\odot$]"
    dev: ["M_{\\rm SMBH, tot}", "Total mass of all SMBHs"]
  cbar-config:
    norm: default
    cmap: plasma
  dev-config:
    default-scale: log
    limits-log: [-0.2, 0.5]
    limits-linear: [0.5, 2.0]

bh-mass:
  default-scale: log
  daq-field-name: CentralBHMass
  label:
    log: "Most massive SMBH mass [$\\log M_\\odot$]"
    linear: "Most massive SMBH mass [$M_\\odot$]"
    dev: ["M_{\\rm SMBH}", "Mass of most massive SMBH"]
  cbar-config:
    norm: default
    cmap: plasma
  dev-config:
    default-scale: log
    limits-log: [-0.5, 0.35]
    limits-linear: [0.0, 4.0]

total-bh-mdot:
  default-scale: log
  daq-field-name: TotalBHMdot
  label:
    log: "SMBH accretion rate [$\\log (M_\\odot / Gyr)$]"
    linear: "SMBH accretion rate [$M_\\odot / Gyr$]"
    dev: ["\\dot{M}_{\\rm SMBH, tot}", "Total SMBH accretion rate"]
  cbar-config:
    norm: default
    cmap: magma
  dev-config:
    default-scale: log
    limits-log: [ -1.5, 1.5 ]
    limits-linear: [ 0.0, 10.0 ]

bh-mode:
  default-scale: log
  daq-field-name: CentralBHMode
  label:
    log: "SMBH mode [$\\log_{10}(\\mu = (\\dot{M} / \\dot{M}_{Edd}) / \\chi)$]"
    linear: "SMBH mode [$\\mu = (\\dot{M} / \\dot{M}_{Edd}) / \\chi$]"
    dev: ["\\mu_{\\rm mode}", "SMBH mode index"]
  cbar-config:
    norm: twoslope
    cmap: ["winter", "autumn"]
    vmin:
      log: -5
      linear: 0
    vmax:
      log: 5
      linear: 10
    vcenter:
      log: 0
      linear: 1
    caps: both
  dev-config:
    default-scale: log
    limits-log: [ -1, 1 ]
    limits-linear: [ 0, 4 ]

bh-cumulative-energy-frac:
  default-scale: log
  daq-field-name: BHCumEnergyFraction
  label:
    log: "Cumulative kinetic energy fraction [$\\log_{10}$]"
    linear: "Cumulative kinetic energy fraction"
    dev: ["E_{\\rm kin} / E_{\\rm tot}", "Energy fraction"]
  cbar-config:
    norm: default
    cmap: cmr.emerald
  dev-config:
    default-scale: log
    limits-log: [-0.2, 0.3]
    limits-linear: [0, 4]

bh-cumulative-energy-total:
  default-scale: log
  daq-field-name: BHCumTotalEnergy
  label:
    log: "Cumulative energy [$\\log(M_\\odot kpc^2 / Gyr^2)$]"
    linear: "Cumulative energy [$M_\\odot kpc^2 / Gyr^2$]"
    dev: ["E_{\\rm cum,tot}", "Injected central SMBH energy"]
  cbar-config:
    norm: default
    cmap: cmr.dusk
  dev-config:
    default-scale: log
    limits-log: [-0.4, 0.4]
    limits-linear: [0, 4]

bh-cumulative-energy-kinetic:
  default-scale: log
  daq-field-name: BHCumKineticEnergy
  label:
    log: "Cumulative kinetic energy [$\\log(M_\\odot kpc^2 / Gyr^2)$]"
    linear: "Cumulative kinetic energy [$M_\\odot kpc^2 / Gyr^2$]"
    dev: ["E_{\\rm cum,kin}", "Injected kinetic energy"]
  cbar-config:
    norm: default
    cmap: cmr.cosmic
  dev-config:
    default-scale: log
    limits-log: [-0.4, 0.4]
    limits-linear: [0, 4]

bh-cumulative-energy-thermal:
  default-scale: log
  daq-field-name: BHCumThermalEnergy
  label:
    log: "Cumulative thermal energy [$\\log(M_\\odot kpc^2 / Gyr^2)$]"
    linear: "Cumulative thermal energy [$M_\\odot kpc^2 / Gyr^2$]"
    dev: ["E_{\\rm cum,th}", "Injected thermal energy"]
  cbar-config:
    norm: default
    cmap: cmr.ember
  dev-config:
    default-scale: log
    limits-log: [-0.3, 0.3]
    limits-linear: [0, 4]

bh-cumulative-mass-frac:
  default-scale: log
  daq-field-name: BHCumMassFraction
  label:
    log: "Cumulative accreted mass fraction [$\\log_{10}$]"
    linear: "Cumulative accreted mass fraction"
    dev: ["M_{\\rm kin} / M_{\\rm tot}", "Accreted mass ratio"]
  cbar-config:
    norm: default
    cmap: magma
  dev-config:
    default-scale: log
    limits-log: [-0.25, 0.6]
    limits-linear: [0, 4]

bh-cumulative-mass-total:
  default-scale: log
  daq-field-name: BHCumTotalMass
  label:
    log: "Cumulative accreted mass [$\\log_{10}(M_\\odot)$]"
    linear: "Cumulative accreted mass [$M_\\odot$]"
    dev: ["M_{\\rm cum,tot}", "Accreted mass"]
  cbar-config:
    norm: default
    cmap: cmr.tree
  dev-config:
    default-scale: log
    limits-log: [-0.4, 0.4]
    limits-linear: [0, 4]

bh-cumulative-mass-kinetic:
  default-scale: log
  daq-field-name: BHCumKineticMass
  label:
    log: "Accreted mass (kinetic mode) [$\\log_{10}(M_\\odot)$]"
    linear: "Accreted mass (kinetic mode) [$M_\\odot$]"
    dev: ["M_{\\rm cum,kin}", "Accreted mass kin. mode"]
  cbar-config:
    norm: default
    cmap: cmr.sapphire
  dev-config:
    default-scale: log
    limits-log: [-0.4, 0.4]
    limits-linear: [0, 4]

bh-cumulative-mass-thermal:
  default-scale: log
  daq-field-name: BHCumThermalMass
  label:
    log: "Accreted mass (thermal mode) [$\\log_{10}(M_\\odot)$]"
    linear: "Accreted mass (thermal mode) [$M_\\odot$]"
    dev: ["M_{\\rm cum,th}", "Accreted mass th. mode"]
  cbar-config:
    norm: default
    cmap: cmr.amber
  dev-config:
    default-scale: log
    limits-log: [-0.3, 0.3]
    limits-linear: [0, 4]

bh-progenitors:
  default-scale: log
  daq-field-name: BHProgenitors
  label:
    log: "Number of SMBH progenitors [$\\log_{10}$]"
    linear: "Number of SMBH progenitors"
    dev: ["N_{\\rm SMBH, prog}", "Progenitors of SMBH"]
  cbar-config:
    norm: default
    cmap: cmr.chroma
    vmin:
      log: 2.0
    caps: min
  dev-config:
    default-scale: log
    limits-log: [-0.3, 0.3]
    limits-linear: [0, 4]

relaxedness-by-distance:
  default-scale: log
  daq-field-name: RelaxednessDist
  label:
    log: "$\\log_{10} (|\\vec{r}_{center} - \\vec{r}_{COM}| / R_{200})$"
    linear: "$|\\vec{r}_{center} - \\vec{r}_{COM}| / R_{200}$"
    dev: ["\\delta r", "relaxedness by distance"]
  cbar-config:
    norm: twoslope
    cmap: ["gray_r", "autumn"]
    vmin:
      log: -2
      linear: 0
    vmax:
      log: 1
      linear: 1
    vcenter:
      log: -1
      linear: 0.1
    caps: both
  dev-config:
    default-scale: log
    limits-log: [ -1, 1 ]
    limits-linear: [ 0, 4 ]

relaxedness-by-mass:
  default-scale: log
  daq-field-name: RelaxednessMass
  label:
    log: "$\\log_{10} (M_{central} / M_{tot})$"
    linear: "$M_{central} / M_{tot}$"
    dev: ["M_{\\rm central} / M_{\\rm tot}", "relaxedness by mass"]
  cbar-config:
    norm: twoslope
    cmap: ["gray_r", "autumn"]
    vmin:
      log: -0.5
      linear: 0.3
    vmax:
      log: 0
      linear: 1
    vcenter:
      log: -0.07058107428570728
      linear: 0.85
    caps: both
  dev-config:
    default-scale: log
    limits-log: [ -0.1, 0.05 ]
    limits-linear: [ 0, 4 ]

formation-redshift:
  default-scale: linear
  daq-field-name: FormationRedshift
  label:
    log: "Redshift [$\\log_{10}(z)$]$"
    linear: "Redshift z"
    dev: ["z_{\\rm form}", "formation redshift"]
  cbar-config:
    norm: default
    cmap: gist_heat
  dev-config:
    default-scale: log
    limits-log: [-1, 0.4]
    limits-linear: [0, 4]

central-cooling-time:
  default-scale: log
  daq-field-name: CentralCoolingTime
  label:
    log: "Central cooling time [$\\log_{10} Gyr$]"
    linear: "Central cooling time [$Gyr$]"
    dev: ["\\rm CCT", "central cooling time"]
  cbar-config:
    norm: default
    cmap: cmr.cosmic
  dev-config:
    default-scale: log
    limits-log: [-1, 1]
    limits-linear: [0, 4]
