name: Tests

on:
  [push, pull_request]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install project
      run: |
        python install.py
    - name: Clone illustris_python
      uses: actions/checkout@v3
      with:
        repository: illustristng/illustris_python
        path: external/illustris_python
    - name: Install illustris_python
      run: |
        python -m pip install --upgrade pip
        cd external/illustris_python/
        pip install .
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Error search with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test library with pytest
      run: |
        cd src/
        pytest
